-- LTC Middleman/Escrow Bot schema
-- Run automatically on startup by db/database.py (idempotent, uses IF NOT EXISTS),
-- or manually via: psql "$DATABASE_URL" -f schema.sql

CREATE TABLE IF NOT EXISTS users (
    discord_id      BIGINT PRIMARY KEY,
    first_seen_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_staff        BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS trades (
    trade_id                BIGSERIAL PRIMARY KEY,
    guild_id                BIGINT NOT NULL,
    channel_id              BIGINT,                 -- ticket channel

    creator_id               BIGINT NOT NULL REFERENCES users(discord_id),
    user1_id                 BIGINT REFERENCES users(discord_id),
    user2_id                 BIGINT REFERENCES users(discord_id),
    sender_id                BIGINT REFERENCES users(discord_id),
    receiver_id               BIGINT REFERENCES users(discord_id),

    user1_gives              TEXT,
    user2_gives               TEXT,
    ltc_amount                NUMERIC(20, 8) NOT NULL DEFAULT 0,

    deposit_address            TEXT,
    deposit_address_index      BIGINT,               -- FK to wallet_addresses.id
    deposit_tx_id              TEXT,
    deposit_confirmations       INTEGER NOT NULL DEFAULT 0,

    receiver_payout_address     TEXT,
    payout_tx_id                TEXT,

    user1_confirmed             BOOLEAN NOT NULL DEFAULT FALSE,
    user2_confirmed             BOOLEAN NOT NULL DEFAULT FALSE,

    status                      TEXT NOT NULL DEFAULT 'CREATED',

    locked_by_staff             BIGINT,               -- staff id if trade is locked
    dispute_opened_by           BIGINT,

    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at                  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_channel ON trades(channel_id);
CREATE INDEX IF NOT EXISTS idx_trades_deposit_address ON trades(deposit_address);

-- Safe migration for databases created by older bot versions.
ALTER TABLE trades ADD COLUMN IF NOT EXISTS trade_value_usd NUMERIC(20, 2);

-- Escrow-controlled deposit addresses. The private key is generated by the
-- bot (via the LTC provider) for a SINGLE trade's escrow deposit -- this is
-- NOT a user's wallet key, it is the service's own custodial key needed to
-- eventually forward funds to the receiver. It is encrypted at rest with
-- WALLET_ENCRYPTION_KEY (Fernet symmetric encryption) and is only ever
-- decrypted in-memory at payout time.
CREATE TABLE IF NOT EXISTS wallet_addresses (
    id                  BIGSERIAL PRIMARY KEY,
    trade_id            BIGINT NOT NULL REFERENCES trades(trade_id),
    address             TEXT NOT NULL UNIQUE,
    encrypted_private_key TEXT NOT NULL,
    network             TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS deposits (
    id                  BIGSERIAL PRIMARY KEY,
    trade_id            BIGINT NOT NULL REFERENCES trades(trade_id),
    tx_id               TEXT NOT NULL,
    address             TEXT NOT NULL,
    amount              NUMERIC(20, 8) NOT NULL,
    confirmations       INTEGER NOT NULL DEFAULT 0,
    detected_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    confirmed_at        TIMESTAMPTZ,
    UNIQUE (trade_id, tx_id)
);

CREATE TABLE IF NOT EXISTS payouts (
    id                  BIGSERIAL PRIMARY KEY,
    trade_id            BIGINT NOT NULL UNIQUE REFERENCES trades(trade_id),
    destination_address TEXT NOT NULL,
    amount              NUMERIC(20, 8) NOT NULL,
    tx_id               TEXT,
    status              TEXT NOT NULL DEFAULT 'PENDING',  -- PENDING, SENT, FAILED, UNKNOWN_REVIEW
    failure_reason      TEXT,
    requested_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at        TIMESTAMPTZ
);
ALTER TABLE payouts ADD COLUMN IF NOT EXISTS failure_reason TEXT;

-- A payout "lock" row exists precisely while a payout is being executed for
-- a trade, preventing a second concurrent release from double-spending.
CREATE TABLE IF NOT EXISTS payout_locks (
    trade_id            BIGINT PRIMARY KEY REFERENCES trades(trade_id),
    locked_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS trade_events (
    id                  BIGSERIAL PRIMARY KEY,
    trade_id            BIGINT NOT NULL REFERENCES trades(trade_id),
    actor_id            BIGINT,               -- discord id of user/staff who caused this, NULL for system
    event_type          TEXT NOT NULL,
    from_status         TEXT,
    to_status            TEXT,
    detail               JSONB,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_trade_events_trade ON trade_events(trade_id);
